### ISSUE TITLE
Chat and chatrooms

### ISSUE THREAD

**Issue by Pawlllosss** [WektorZabrze/DjangoManagementSite#1]
I've started work on providing chat. I'm following this tutorial: https://gearheart.io/blog/creating-a-chat-with-django-channels/.

For now I've provided a websocket connection and a simply chat room model. Right now the chat room is displayed in the _uniformed_view_, which was modified(I've added `<br>` tag to provide new line - it's a poor solution) as well as index in _user view_(to which i added  `chat_rooms = ChatRoom.objects.order_by("room_name")` line to provide a possibility to display all rooms).

I've updated the requirements so it passes the Travis build, however if you run it locally the below command may by found necessary:
sudo apt-get install redis-server

**Comment by Pawlllosss** [comment]
I've provided the next update on developing the chat feature. For now the most basic part of chat backend is completed. It's possible to join and leave rooms through websocket, by clicking the name of room on the main website. 

If you check your browser log you will see information encoded in json about leaving or joining the room. Currently, very basic front end is provided by java script - however it should be changed. Sending and receiving message is possible, but to see message content you have to check browser log.

Still chat is only shown in the _uniformed_view.html_ (it would be good to create a base template in which chat window is provided). New chats are appearing beetween these tags  ```<div id="chats"><!-- there will be desplayed chats after joining room --></div>```

**TO DO:**

- Create the front-end
- Create the Direct Messages
- Create and deleting chat rooms by users
- Create chatroom only for selected position or invited users

**Comment by mrcmis** [comment]
I've provided functionality allowing logged users to create chat rooms. Chat view is now based on .js file provided by @Pawlllosss and should be modified in future. We'll have to modify a ChatForm in forms.py to add functionality such as creating chatroom only for selected position etc. And of course, frontend.

**Comment by Pawlllosss** [comment]
Created basic fronted for chat-room. It displays author messages and information about joining and leaving room on the right and messages from other users on the left.

**TO DO:**
- Hide java variables from HTML (now it's not injection proof)
- Display chat in the new window
- Modify css so messages about joining and leaving room will be displayed in different colour.

**Comment by Loniowsky** [comment]
Good job!
